### ISSUE TITLE
Proposals Can Incorrectly Reach VOTING_FINISHED when Quorum Failed

### ISSUE THREAD

**Issue by audieleon** [VitaDAO/VitaDAO-contracts#29]
**Describe the bug**
On Rinkeby, the contracts are deployed at 
```
REACT_APP_TOKEN=0x8a09C5e21254C7537000aD3577C2367C0a9502EC
REACT_APP_RAPHAEL_ADDRESS=0x1C27e2955dEAf2fbfe7D54DE741581856D939885
REACT_APP_STAKING_ADDRESS=0x757B9bC638f078454CD55ee5d9805eA51121e455
```

Proposal 12 reached an incorrect state. Minimum voted needed was set at 1000 votes, and I voted with 740
votes. This should result in a proposal status of `5` or `QUORUM_FAILED` - but it didn't. It ended with a status of `2` or `VOTES_FINISHED`.

**Expected behavior**
If the quorum failed for a proposal, then upon updating the status, it should always and without fail reach the `QUORUM_FAILED` status. 

**Screenshots**
![image](https://user-images.githubusercontent.com/2258619/124378149-912f1b80-dc75-11eb-9c3b-138e24782e7a.png)

**Comment by wschwab** [comment]
do you know what the full sequence of contract calls was? I'm assuming it started:
1) `createProposal`
2) wait for pre-vote period to end, `updateProposalStatus`
3) `vote`

but do you know what happened next? Was `updateProposalStatus` called during the voting period, or did you wait until after? Any other calls I should know about?

**Comment by audieleon** [comment]
Relevant calls: 
setMinVotesNeeded(1000) - Jul-01-2021 08:05:54 AM +UTC - [Etherscan](https://rinkeby.etherscan.io/tx/0x200a01b178737722a20c8ad030264136fe279b96333af960c96be96d2d2eef34)
createProposal(12) - Jul-02-2021 05:43:21 AM +UTC - [Etherscan](https://rinkeby.etherscan.io/tx/0xa93e3b7b47e12d77159799c66971ef6f56dcd89fa6a1f077ac12cbba9aaccf4a)
updateProposalStatus(12) - Jul-02-2021 05:49:21 AM +UTC - [Etherscan](https://rinkeby.etherscan.io/tx/0x4f0a5a5ca875147c485070eff6a0845439a4c414b3205bb92ec1b8bc5f842a23)
vote(12) - Jul-02-2021 05:50:36 AM +UTC - [Etherscan](https://rinkeby.etherscan.io/tx/0x02bb27c15c1857304771e6ecc92ad6dab501d1894a42c0b1750bf11db9f7f1e4)
updateProposalStatus(12) - Jul-02-2021 09:33:47 AM +UTC - [Etherscan](https://rinkeby.etherscan.io/tx/0x1ed68fe72bda8787f03e09c5e84b9fcf29c96c3239d49c47cd993944144ebfd9)

At the time of running this proposal, the voting duration was set to 69 blocks ([Etherscan](https://rinkeby.etherscan.io/tx/0x7ba2261440d0008120b589b3de34265a9c8721dd9704468e88bd5c7adf4c8d94)) so the last update call was definitely after the duration. 

The full catalog of calls to this contract is [available here](https://rinkeby.etherscan.io/txs?a=0x1C27e2955dEAf2fbfe7D54DE741581856D939885), and consists of around 55 txns including errors.

**Comment by wschwab** [comment]
I wrote a longer explanation in the Discord, but I believe the contract is still working as expected. If 1000 is entered to `setMinVotesNeeded` through the Etherscan interface (which looks to be the case from the link to `setMinVotesNeeded`), then the threshold doesn't become 1000 Vita, it rather becomes 1000 * `1e-18` Vita. You'd need to put this number (1000 * `1e18`) into Etherscan to get a threshold of 1000 Vita:
```
1000000000000000000000
```

**Comment by audieleon** [comment]
I really hope this is true. It would explain why I couldn't find fault with the logic in that nested conditional. 

However, I definitely want to confirm this, since for the proposal index (also a unit256) I don't need to enter the extra digits or treat the number in anyway to get results. I tried at first to set using the additional digits, and it failed.

**Comment by wschwab** [comment]
> for the proposal index (also a unit256) I don't need to enter the extra digits or treat the number in anyway to get results

This also makes sense. Proposal numbers don't have decimals - they're discrete, so there's no need to pad 18 0s to the right. I can show where in the token contract the magic happens that pads each Vita with 18 decimal places (necessitating putting the 18 zeroes in) if you like - since it's standard practice with ERC20 tokens, it's kinda abstracted away.

**Comment by audieleon** [comment]
William was correct.
